DROP TABLE mytable;
CREATE TABLE mytable(
  ID INTEGER(3) NOT NULL PRIMARY KEY 
, Name VARCHAR(73)
, Health_Type VARCHAR(21)
, Address VARCHAR(53)
, Location VARCHAR(22)
, City VARCHAR(7)
, State VARCHAR(14)
, PhoneNumbers VARCHAR(43)
, Email VARCHAR(72)
, Description VARCHAR(570)
, Point_1 VARCHAR(21)
, Point_2 VARCHAR(21)
);
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (1,'HOSPITAL MUNICIPAL CARLOS TORTELLY','Hospital','Rua Des. Athayde Parreira, 266 - Centro','Centro','Niterói','Rio de Janeiro','2729-9300; 2729-9343; 2729-9340','direcao.hmct@saude.niteroi.rj.gov.br; admin.hmct@saude.niteroi.rj.gov.br','Emergência 24 horas.','-22.8689,-43.085632','-22.893911,-43.10896');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (2,'HOSPITAL GETÚLIO VARGAS','Hospital','Rua Teixeira de Freitas s/nº - Fonseca','Fonseca','Niterói','Rio de Janeiro','2627-1535; 2627-1525; 2627-1543','direcao.hgfv@saude.niteroi.rj.gov.br; admin.hgvf@saude.niteroi.rj.gov.br','Emergência pediátrica, porta aberta 24 horas.','-22.892089,-43.108335','-22.875141,-43.075875');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (3,'HOSPITAL ORÊNCIO DE FREITAS','Hospital','Av.Machado s/nº - Barreto','Barreto','Niterói','Rio de Janeiro','2620-5157; 2620-3434','direcao.hof@saude.niteroi.rj.gov.br; admin.hof@saude.niteroi.rj.gov.br','Emergência 24 horas para atendimento a cirurgias abdominais. Conta com outros serviços de cirurgias como ginecológicas, urológicas, vasculares e com vídeolaparoscopia em caráter eletivo.','-22.87493,-43.075805','-22.86317,-43.09393');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (4,'HOSPITAL PSIQUIÁTRICO JURUJUBA','Saúde Mental','Av.Quintino Bocaiúva, s/nº - Charitas','Charitas','Niterói','Rio de Janeiro','2714-8856; 2710-0663; 2610-7678','direcao.hpj@saude.niteroi.rj.gov.br; admin.hpj@saude.niteroi.rj.gov.br','Emergência 24 horas para o atendimento psiquiátrico do município.','-22.86317,-43.09393','-22.923161,-43.09448');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (5,'MATERNIDADE ALZIRA REIS','Hospital','Av.Carlos Ermelindo Marins s/nº - Jurujuba','Jurujuba','Niterói','Rio de Janeiro','3611-0107; 3701-1846','direcao.mar@saude.niteroi.rj.gov.br; admin.mar@saude.niteroi.rj.gov.br','Referência para gestantes de baixo risco no município. Emergência 24 horas.','-22.926164,-43.094773','-22.931781,-43.11545');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (6,'POLICLÍNICA REGIONAL DR. CARLOS ANTÔNIO DA SILVA','Policlinica','Rua Jansen de Mello s/nº - São Lourenço','São Lourenço','Niterói','Rio de Janeiro','2717-1426; 2719-0050','prcas@saude.niteroi.rj.gov.br;','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Odontologia, Nutrição, Dermatologia, Neurologia adulto e infantil, Núcleo de Saúde Mental, Ecocardiograma e Eletrocardiograma, Alergista, Psicologia, Endodontia, Assistência Social, Periodontia, Hepatologia, Fisioterapia, Farmácia, Terapeuta Ocupacional, Psiquiatria, Infectologia, Fonoaudiologia, Vacinação básica, Teste do pezinho e PPD e orelhinha, Teste de Investigação de gravidez (TIG).','-22.946456,-43.032265','-22.884228,-43.115557');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (7,'POLICLÍNICA REGIONAL DR. SÉRGIO AROUCA','Policlinica','Praça Vital Brazil s/nº - Santa Rosa','Santa Rosa','Niterói','Rio de Janeiro','2610-8975; 2711-2366; 2710-9176','prsa@saude.niteroi.rj.gov;','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Odontologia, Nutrição, Dermatologia, Neurologia, Alergista, Psicologia, Assistência Social, Reumatologia, Fisioterapia, Cardiologia, Terapeuta Ocupacional, Fonoaudiologia, Núcleo de Saúde Mental, Infectologia, Farmácia, Vacinas básicas, Teste de Investigação de Gravidez (TIG), Teste do Pezinho e Turbeculose (TB).','-22.902038,-43.095465','-22.908704,-43.09595');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (8,'POLICLÍNICA REGIONAL DR. GUILHERME TAYLOR MARCH','Policlinica','Rua Desembargador Lima Castro, 238 - Fonseca','Fonseca','Niterói','Rio de Janeiro','2626-4170','prgmarch@saude.niteroi.rj.gov.br;','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Odontologia, Nutrição, Dermatologia, Neurologia, Psicologia, Assistência Social, Homeopatia, Endocrinologia, Pneumologista, Fisioterapia, Terapia Ocupacional, Fonoaudiologia, Cardiologista, Farmácia, Eletrocardiograma, Exame do pezinho e triagem comportamental, Vacinas básicas, grupos:  idosos, mamãe e bebê, Planejamento Familiar, Hipertensão e Diabetes, Gestante e Teste de Investigação de Gravidez (TIG), Hanseníase, Tuberculose, Sisvon, Urologista, Teste do Olhinho e Orelhinha, Neurologista (só adulto).','-22.931781,-43.11545','-22.888053,-43.088222');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (9,'POLICLÍNICA REGIONAL DO LARGO DA BATALHA DR. FRANCISCO DA CRUZ NUNES','Policlinica','Rua Ver.Armando Ferreira, 30 - Largo da Batalha','Largo da Batalha','Niterói','Rio de Janeiro','2616-3633; 2710-1053; 2710-7100','prlbatalha@saude.niteroi.rj.gov.br;','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Odontologia, Endocrinologia, Nutrição, Dermatologia, Alergista, Fonoaudiologia ,Fisioterapia, Assistência Social, Infectologia, Geriatria, Neurologia, Cardiologista, RX, Coleta domiciliar , Teste do Pezinho e Orelhinha, Teste de Investigação de Gravidez (TIG), Programa de Tabagismo, Saúde da mulher, Hiperdia, Urologista.','-22.888056,-43.088229','-22.898099,-43.077778');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (10,'POLICLÍNICA REGIONAL DE ITAIPU ASSISTENTE SOCIAL MARIA APARECIDA DA COSTA','Policlinica','Est.Engenho do Mato s/nº - Itaipu','Itaipu','Niterói','Rio de Janeiro','2609-6368; 2709-1579','pritaipu@saude.niteroi.rj.gov.br;','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Odontologia, Endocrinologia, Dermatologia, Nutrição, Psicologia, Fonoaudiologia, Fisioterapia, Assistência Social, Neurologia, Fisioterapia, Ultrassonografia, Eletrocardiograma, Todos os testes comportamentais, Teste do Pezinho e Reflexo Vermelho, Terapia Ocupacional, Homeopatia, Ambulatório de feridas, Saúde do idoso, Hipertensão e Diabetes, Acupuntura , Teste de Investigação de Gravidez (TIG), Geriatria, Ortopedia, Urologia, Grupo de Hipertensão e Diabetes, Saúde da Mulher.','-22.888234,-43.065484','-22.929421,-43.00804');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (11,'POLICLÍNICA REGIONAL DA ENGENHOCA DR. RENATO SILVA','Policlinica','Avenida João Brasil, s/nº - Engenhoca','Engenhoca','Niterói','Rio de Janeiro','2628-8047; 3603-8874','prengenhoca@saude.niteroi.rj.gov.br;','Odontologia, Endocrinologia, Nutrição, Dermatologia, Alergista, Fonoaudiologia, Fisioterapia, Assistência Social, Infectologia, Ortopedia, Geriatria, Neurologia, Cardiologista, Teste do Pezinho e Orelhinha, Urologista, Psicologia, Hanseníase, DST, Hiperdia e Tuberculose.','37.0625,-95.677068','-22.871717,-43.094092');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (12,'POLICLÍNICA COMUNITÁRIA ILHA DA CONCEIÇÃO','Policlinica','Rua Jornalista Sardo Filho, 196 - Ilha da Conceição','Ilha da Conceição','Niterói','Rio de Janeiro','2620-6671; 2620-5333','pcilha@saude.niteroi.rj.gov.br;','Odontologia, Nutrição, Cardiologista, Endocrinologia, Fonoaudiologia, Neurologia, Vacinas básicas, Teste do Pezinho , Eletrocardiograma, Farmácia, Teste de Investigação de Gravidez (TIG), Psicologia.','-22.889598,-43.115587','-22.872429,-43.115393');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (13,'POLICLÍNICA COMUNITÁRIA DE JURUJUBA','Policlinica','Av. Carlos Ermelindo Marins s/nº - Jurujuba','Jurujuba','Niterói','Rio de Janeiro','2704-9638; 2704-9668','pcjurujuba@saude.niteroi.rj.gov.br;','Odontologia, Nutrição, Cardiologia, Endocrinologia, Dermatologia, Psicologia, Neurologia, Alergista, Reumatologia, Fisioterapia, Vacinas Básicas, Exame do Pezinho, Eletrocardiograma, RX Dentário, BCG, Terapia Ocupacional, Fonoaudiologia.','-22.908704,-43.09595','-22.931781,-43.11545');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (14,'POLICLÍNICA COMUNITÁRIA DO CANTAGALO PROFESSOR BARROS TERRA','Policlinica','Rua Alcebíades Pinto, s/nº - Cantagalo','Cantagalo','Niterói','Rio de Janeiro','2616-6608','pccantagalo@saude.niteroi.rj.gov.br;','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Odontologia, Nutrição, Teste de Investigação de Gravidez (TIG), Terapia Ocupacional, Fonoaudiologia, Psicólogo, Teste do Pezinho, BCG, Farmácia, Vacinas Básicas, Homeopatia, Saúde da Gestante, Hiperdia, Sisvon.','-22.893473,-43.122261','-22.907761,-43.0521');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (15,'POLICLÍNICA DE ESPECIALIDADES EM ATENÇÃO A SAÚDE DA MULHER MALÚ SAMPAIO','Policlinica','Rua Visconde de Uruguai, 531 - Centro','Centro','Niterói','Rio de Janeiro','2621-2302; 2621-1109 (fax); 2621-8185 (SAU)','pems@saude.niteroi.rj.gov.br;','Ultra de Mama, obstétrica, Patologia Cervical e Mamária, Infertilidade Conjugal, Obstetrícia de alto risco, Cirurgia Ambulatorial de  Patologia Cervical, Fisioterapia de apoio a pacientes mastectomizadas, Nucleo de Atenção Especial a Criança e ao Adolescente, Psicologia, Assistente social, Laboratório de Copocitopatologia.','-22.929899,-43.008041','-22.893533,-43.122265');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (16,'POLICLÍNICA DE ESPECIALIDADES DR. SYLVIO PICANÇO','Policlinica','Av. Amaral Peixoto, 169 - Centro','Centro','Niterói','Rio de Janeiro','2719-1699; 2719-3255; 2620-0486 (fax)','pesp@saude.niteroi.rj.gov.br;','E.C.C, Eco cardiograma, Eletro encefalograma, Mamografia, Cardiologia, Serviço de Atendimento Auditivo (SASA), Fonoaudiologia, Otorrino, Farmácia, Psicologia, Assistente Social, Neurologia, Pneumologia, Endócrino, Angiologia, Gastroenterologia, Fisioterapia, Dermatologia, Proctologia, Hematologia, Oftalmologia, Acupuntura.','-22.893533,-43.122265','-22.893533,-43.122265');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (17,'UNIDADE DE URGÊNCIA MÁRIO MONTEIRO','Urgência e Emergência','Estrada Francisco da Cruz Nunes s/nº - Itaipú','Itaipú','Niterói','Rio de Janeiro','2619-2613','direcao.umam@saude.niteroi.rj.gov.br; admin.umam@saude.niteroi.rj.gov.br','Capacidade para o atendimento e estabilização de casos graves. Atendimento a acidentados. Não é Unidade Hospitalar, mas sim, pré-hospitalar. Urgências 24 horas.','-22.931781,-43.11545','-22.946456,-43.032265');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (18,'UPA 24h NITEROÍ','Urgência e Emergência','Rua Sá Barreto nº 107, Fonseca.','Fonseca','Niterói','Rio de Janeiro','2625-7807; 2625-7721','','Urgências 24 horas.','-22.880885,-43.078836','-22.884122,-43.083229');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (19,'SPA 1 - SERVIÇO DE PRONTO ATENDIMENTO DO LARGO DA BATALHA','Urgência e Emergência','Rua Vereador Armando Ferreira, 30 - Largo da Batalha','Largo da Batalha','Niterói','Rio de Janeiro','2616-3633; 2616-0130','','Urgências 24 horas.','-22.929939,-43.285446','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (20,'SPA 2 - SERVIÇO DE PRONTO ATENDIMENTO DA ENGENHOCA','Urgência e Emergência','Avenida Professor João Brasil, S/Nº - Engenhoca','Engenhoca','Niterói','Rio de Janeiro','3603-8874; 2628-8047','','Urgências 24 horas.','-22.905728,-43.068174','-22.870916,-43.093486');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (21,'HOSPITAL ESTADUAL AZEVEDO LIMA','Urgência e Emergência','Rua Teixeira Freitas, 30 - Fonseca','Fonseca','Niterói','Rio de Janeiro','2299-9034','','Emergências 24 horas.','-22.884122,-43.083229','-22.88088,-43.07883');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (22,'JESUS MONTAÑEZ - PMF PALÁCIO','Médico de Família','Rua 11 de Agosto, nº 4 - Ingá','Ingá','Niterói','Rio de Janeiro','2722-0146','pmfinga@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (23,'CÉLIA SANCHEZ - PMF ILHA DA CONCEIÇÃO','Médico de Família','Rua Jornalista Sardo Filho, 196 - Ilha da Conceição','Ilha da Conceição','Niterói','Rio de Janeiro','2620-6671; 2620-5333','pmfilha@saude.niteroi.rj.gov.br;','','-22.747316,-43.31161','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (24,'CAMILO CIENFUEGOS - PMF VIRADOURO','Médico de Família','Rua Mario Viana, 790 - Viradouro','Viradouro','Niterói','Rio de Janeiro','2711-8369','pmfviradouro@saude.niteroi.rj.gov.br;','','-22.929421,-43.00804','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (25,'JOSÉ ANTONIO ECHEVERRIA BIANCHI - PMF SOUZA SOARES','Médico de Família','Rua Lions Club, 37 - Santa Rosa','Santa Rosa','Niterói','Rio de Janeiro','3602-0083','pmfssoares@saude.niteroi.rj.gov.br;','','-22.905801,-43.079541','-22.906104,-43.090203');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (26,'CARLOS J. FINLAY - PMF VITAL BRAZIL','Médico de Família','Rua João da Lossi - Trav. F nº 8 - Vital Brasil','Vital Brasil','Niterói','Rio de Janeiro','2610-1904','pmfvbrazil@saude.niteroi.rj.gov.br;','','-22.906005,-43.092799','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (27,'FRANK PAÍS GARCIA - PMF CAVALÃO','Médico de Família','Alameda Paris s/nº - São Francisco','São Francisco','Niterói','Rio de Janeiro','2611-9570','pmfcavalao@saude.niteroi.rj.gov.br;','','-22.907311,-43.09405','-22.913199,-43.104472');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (28,'ABEL SANTAMARIA - PMF PREVENTÓRIO I','Médico de Família','Travessa Carmita s/nº - Charitas','Charitas','Niterói','Rio de Janeiro','2715-4313','pmfpreventorio1@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (29,'CALIXTO GARCIA - PMF PREVENTÓRIO II','Médico de Família','Av.Quintino Bocaiúva s/nº - Charitas','Charitas','Niterói','Rio de Janeiro','3701-0161','pmfpreventorio2@saude.niteroi.rj.gov.br;','','-22.93646,-43.091533','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (30,'MÁRIO MUNHOZ MONROE - PMF JURUJUBA (Carcarejo)','Médico de Família','Av.Carlos Ermelindo Marins s/nº - Jurujuba','Jurujuba','Niterói','Rio de Janeiro','2704-9638; 2704-9668','','','-22.923161,-43.09448','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (31,'JOSÉ SUÁREZ BLANCO - PMF JONATHAS BOTELHO','Médico de Família','Trav.Jonathas Botelho, 133 - Cubango','Cubango','Niterói','Rio de Janeiro','2710-6367','pmfjbotelho@saude.niteroi.rj.gov.br;','','-14.239424,-53.186502','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (32,'PMF LAGOINHA','Médico de Família','Av.Colônia s/nº - Cubango','Cubango','Niterói','Rio de Janeiro','2625-9467','pmflagoinha@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (33,'JÚLIO DIAZ GONZALEZ - PMF LEOPOLDINA','Médico de Família','Rua George Allan s/nº - Largo dos Barradas - Barreto','Barreto','Niterói','Rio de Janeiro','2624-0017','pmfleopoldina@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (34,'CARLOS RAFAEL RODRIGUES - PMF MARÍTIMOS','Médico de Família','Av. Machado, s/nº - Barreto','Barreto','Niterói','Rio de Janeiro','3703-3265','pmfmaritimos@saude.niteroi.rj.gov.br;','','-22.881133,-43.082978','-22.863423,-43.093936');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (35,'JORGE LUIZ CAMACHO RODRIGUES - PMF MARUÍ','Médico de Família','Rua Monsenhor Raeder, 151 - Barreto','Barreto','Niterói','Rio de Janeiro','3714-2173','pmfmarui@saude.niteroi.rj.gov.br;','','-22.863423,-43.093936','-22.866033,-43.107734');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (36,'ANTÔNIO LÔPEZ - PMF NOVA BRASÍLIA','Médico de Família','Rua Professor João Brasil, 1726 - Engenhoca','Engenhoca','Niterói','Rio de Janeiro','3706-7519','pmfnbrasilia1@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (37,'WILMA ESPIN - PMF VILA IPIRANGA','Médico de Família','Rua Tenente Osório, s/nº  Fonseca','Fonseca','Niterói','Rio de Janeiro','2625-3821','','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (38,'HAIDÉE SANTAMARIA I - PMF CANTAGALO','Médico de Família','Estrada Francisco Cruz Nunes s/nº - Cantagalo','Cantagalo','Niterói','Rio de Janeiro','2616-5037','pmfcantagalo1@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (39,'SALVADOR ALLENDE - PMF ATALAIA','Médico de Família','Rua Padre José Euger - s/nº - Atalaia','Atalaia','Niterói','Rio de Janeiro','2618-7616','pmfatalaia@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (40,'DR. WILSON DE OLIVEIRA - PMF ITITIOCA','Médico de Família','Rua Vila Costa Monteiro s/nº - Ititioca','Ititioca','Niterói','Rio de Janeiro','2610-0852','pmfititioca@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (41,'WILLIAN SOLLER I - PMF ENGENHO DO MATO','Médico de Família','Estrada Irene Lopes Sodré s/nº - Engenho do Mato','Engenho do Mato','Niterói','Rio de Janeiro','2709-5222','pmfemato1@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (42,'ERNESTO CHE GUEVARA I - PMF CAFUBÁ I','Médico de Família','Av.Raúl de Oliveira Rodrigues, S/Nº - Cafubá','Cafubá','Niterói','Rio de Janeiro','2619-0757','pmfcafuba1@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (43,'ERNESTO CHE GUEVARA II - PMF CAFUBÁ II','Médico de Família','Rua Vereador Luiz Erthal, Lt. 05, Qd. 69 - Cafubá','Cafubá','Niterói','Rio de Janeiro','2619-5268','pmfcafuba2@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (44,'ALBERTO RICARDO HATIN - PMF CAFUBÁ III','Médico de Família','Rua Manoel Pacheco de Carvalho 107 - Piratininga','Piratininga','Niterói','Rio de Janeiro','2709-4374','pmfcafuba3@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (45,'CTE. MANOEL PIÑEIRO LOZADA - PMF MARAVISTA','Médico de Família','Rua Astor da Costa Menezes, S/Nº - Maravista','Maravista','Niterói','Rio de Janeiro','2709-0360','pmfmaravista@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (46,'PMF COLONIA','Médico de Família','Praia de Itaipu - Colônia dos Pescadores','Colônia dos Pescadores','Niterói','Rio de Janeiro','2609-4332','pmfcolonia@saude.niteroi.rj.gov.br;','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (47,'DR. OMAR MARINHO VIEIRA - PMF ALARICO DE SOUZA','Médico de Família','Estrada Alarico de Souza, s/nº - Santa Rosa','Santa Rosa','Niterói','Rio de Janeiro','','','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (48,'RAUL CARLOS PARETO JR. - PMF BERNARDINO','Médico de Família','Rua Sá Barreto, nº 107 - Fonseca - ao lado da UPA','Fonseca','Niterói','Rio de Janeiro','','','','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (49,'UBS CENTRO DR. EDUARDO IMBASSAY','Postos de Saúde','Rua Visconde de Uruguai, 531 - Centro','Centro','Niterói','Rio de Janeiro','2620-8226; 2612-8183','ubscentro@saude.niteroi.rj.gov.br;','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Odontologia, Nutrição, Psicologia, Fonoaudiologia , Serviço Social, Vacinas básicas, Teste do Pezinho, Farmácia, Teste de Investigação de Gravidez (TIG), BCG, Hiperdia, Homeopatia e Puericultura.','-22.929899,-43.008041','-22.893533,-43.122265');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (50,'UBS MORRO DO ESTADO DR. MARIO PARDAL','Postos de Saúde','Rua Araujo Pimenta s/nº','Centro','Niterói','Rio de Janeiro','2622-1010','ubsestado@saude.niteroi.rj.gov.br;','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Odontologia, Nutrição, Serviço Social, Vacinas básicas, Teste do Pezinho, Teste de Investigação de Gravidez (TIG), Farmácia, BCG e Teste do Olhinho.','-22.893533,-43.122265','-22.893591,-43.122239');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (51,'UBS SANTA BÁRBARA ADELINO DE MENDONÇA E SILVA','Postos de Saúde','Av.Prof.João Brasil s/nº - Engenhoca','Engenhoca','Niterói','Rio de Janeiro','3603-8874; 2628-8047','ubsengenhoca@saude.niteroi.rj.gov.br;','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Odontologia, Nutrição, Núcleo de Saúde Mental, Grupo Hipertensão e Diabetes, Saúde da Gestante, Serviço Social, Vacinas básicas, Teste do Pezinho , Eletrocardiograma , Farmácia, Fonoaudiologia, Teste de Investigação de Gravidez (TIG), Programas de Tabagismo, Adolescente, Idoso, Saúde da Mulher, Saúde Bucal, Imunização e Teste da Orelhinha.','-22.899976,-43.119857','-22.875499,-43.053557');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (52,'UBS – BARRETO – Dr. João da Silva Vizella','Postos de Saúde','Rua Luiz Palmier, 726 - Barreto','Barreto','Niterói','Rio de Janeiro','2719-0141; 2719-6861','ubsbarreto@saude.niteroi.rj.gov.br;','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Nutrição, Cardiologia, Serviço Social, Vacinas Básicas, Teste do Pezinho, Eletrocardiograma, Laboratório, Farmácia, Fonoaudiologia, Planejamento familiar, Grupo de Hipertensão e Diabetes, Teste de Investigação de Gravidez (TIG), PPD, Grupo de Gestante, Psicologia, Terapeuta Ocupacional, Infectologista, Tabagismo, Odontologia.','-22.871094,-43.099279','-22.861585,-43.09508');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (53,'UBS – BALDEADOR DEPUTADO JOSÉ SALLY','Postos de Saúde','Lot.Bento Pestana s/nº - Morro do Castro','Baldeador','Niterói','Rio de Janeiro','2624-1224; 2722-3761','ubsbaldeador@saude.niteroi.rj.gov.br;','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Odontologia, Nutrição, Psicologia, Serviço Social, Vacinas básicas, Teste do Pezinho , Farmácia, Teste de Investigação de Gravidez (TIG).','-22.87317,-43.068295','-22.873131,-43.068295');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (54,'UBS PIRATININGA DOM LUIZ ORIONE','Postos de Saúde','Av. dos Pescadores - Lotes 2,3 e 4 - Piratininga','Piratininga','Niterói','Rio de Janeiro','2618-2654','ubspiratininga@saude.niteroi.rj.gov.br;','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Odontologia, Nutrição, Psicologia, Fonoaudiologia, Serviço Social, Vacinas Básicas , Teste do Pezinho , Farmácia, Teste de Investigação de Gravidez (TIG), Teste do Olhinho e Triagem Auditiva.','-22.93899,-43.066707','-22.946171,-43.09322');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (55,'UBS – VARZEA DAS MOÇAS DR. TOBIAS TOSTES MACHADO','Postos de Saúde','Estrada Velha de Maricá s/nº - Várzea das Moças','Várzea das Moças','Niterói','Rio de Janeiro','3602-8057','ubsvmocas@saude.niteroi.rj.gov.br;','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Odontologia, Homeopatia, Nutrição, Serviço Social, Vacinas básicas, Teste do Pezinho, Farmácia, Fonoaudiologia, Teste de Investigação de Gravidez (TIG), Programa de Tabagismo e Teste da Orelhinha.','-22.933758,-43.016065','-22.902533,-42.964462');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (56,'UBS – ENGENHOCA – Policlínica Regional Norte II Dr.Renato Silva','Postos de Saúde','Av.Prof.João Brasil s/nº - Engenhoca','Engenhoca','Niterói','Rio de Janeiro','3603-8874 – 2628-8047','ubsengenhoca@saude.niteroi.rj.gov.br','Consultas básicas (Clínica Médica, Pediatria, Ginecologia), Odontologia, Nutrição, Núcleo de Saúde Mental, Grupo Hipertensão e Diabetes, Saúde da Gestante, Serviço Social, Vacinas básicas, Teste do Pezinho , Eletrocardiograma , Farmácia, Fonoaudiologia, Teste de Investigação de Gravidez (TIG), Programas de Tabagismo, Adolescente, Idoso, Saúde da Mulher, Saúde Bucal, Imunização e Teste da Orelhinha.','-22.87038,-43.09347','-22.87004,-43.10447');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (57,'CAPS Casa do Largo','Saúde Mental','R. Nilo de Freitas, 41.Lgo. Batalha','Largo da Batalha','Niterói','Rio de Janeiro','2616-5612/2718-0229','','Atende os bairros Matapaca, Mª Paula, Jacaré, Ititioca, Lgo. da Batalha, Vila Progresso, Badú, Pendotiba, Várzea das Moças, Rio do Ouro, Sapê, Piratininga, Cafubá, Itaipu, Cantagalo, Maceió, Itacoatiara, Muriqui, Camboinhas, Engenho do Mato, Viçoso Jardim.','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (58,'CAPS Herbert de Souza','Saúde Mental','R. Marques de Olinda, 104. Centro','Centro','Niterói','Rio de Janeiro','2722-4147/2622-1533','','Atende os bairros do Centro, São Domingos, Morro do Estado, Ilha da Conceição, São Lourenço, Sta. Bárbara, Ponta d’Areia, Bairro de Fátima, Ingá, Caramujo, Fonseca (até a rua 22 de Novembro), Vila Pereira Carneiro.','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (59,'CAPS AD Alameda','Saúde Mental','Alameda São Boaventura, 129. Fonseca','Fonseca','Niterói','Rio de Janeiro','2718-5803','','Referência para todo o município de Niterói.','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (60,'CAPSi Monteiro Lobato','Saúde Mental','R. Tiradentes, 18. Ingá','Ingá','Niterói','Rio de Janeiro','2620-0318/2621-6598','','Referência para todos os bairros de Niterói.','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (61,'Amb. Engenhoca','Saúde Mental','R. Pça Vital Brasil s/ no.Vital Brasil','Vital Brasil','Niterói','Rio de Janeiro','2711-2366/2710-9176/2610-8975','','Atende os bairros Sta. Rosa, Vital Brasil, Viradouro, Pé Pequeno, Cubango, Icaraí, Ingá, Boa Viagem, São Domingos, Gragoatá.','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (62,'Amb. Carlos Antônio da Silva','Saúde Mental','Av. Jansen de Melo s/ no.Centro','Centro','Niterói','Rio de Janeiro','2719-0050/2717-1426','','Atende os bairros Centro, Bairro de Fátima, Ilha da Conceição, Vila Pereira Carneiro, Ponta d’Areia, Portugal Pequeno, São Lourenço, Santana (Ponto Cem Réis), Fonseca (até a rua 22 de Novembro), Morro do Estado, Caramujo, Sta. Bárbara.','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (63,'Amb. Jurujuba','Saúde Mental','Av. Quintino bocaiúva s/ no.Charitas','Charitas','Niterói','Rio de Janeiro','2714-8856  Ramal: 223','','Atende Cascarejo, Cachoeira, Morro do Cavalão, São Francisco, Preventório, Charitas, Grota do Surucucu,Jurujuba.','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (64,'Amb. Pendotiba','Saúde Mental','R. Miguel Pereira Sarmento, 3/204 – Pendotiba','Pendotiba','Niterói','Rio de Janeiro','2616-1456','','Atende Matapaca, Mª Paula, Jacaré, Ititioca, Lgo. da Batalha, Vila Progresso, Badú, Pendotiba, Várzea das Moças, Rio do Ouro, Sapê, Piratininga, Cafubá, Itaipu, Cantagalo, Maceió, Itacoatiara, Muriqui, Camboinhas, Engenho do Mato, Viçoso Jardim.','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (65,'R. Terapêutica Pendotiba','Saúde Mental','Est. Caetano Monteiro, 253 – Pendotiba','Pendotiba','Niterói','Rio de Janeiro','2616-8722','','Atende todo o municipio','','');
INSERT INTO mytable(ID,Name,Health_Type,Address,Location,City,State,PhoneNumbers,Email,Description,Point_1,Point_2) VALUES (66,'R. Terapêutica Fonseca','Saúde Mental','R. Magnólia Brasil, 55 casa 1 – Fonseca','Fonseca','Niterói','Rio de Janeiro','2626-2231','','Atende todo o municipio','','');
